# -*- coding: utf-8 -*-
"""test 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiA9FcMhuLQCyx6s2oYG9ICPKIsUDRaQ
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("task 1.xlsx")

from google.colab import files

uploaded = files.upload()

df.head()

print(df.tail())
print(df.info())

print(df.isnull().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

print(df.head(10))

print("Highest Price:", df["High"].max())
print("Lowest Price:", df["Low"].min())
print("Average Closing Price:", df["Close"].mean())

df["Daily Price Change"] = df["Close"].diff()

print(df[["Date", "Close", "Daily Price Change"]])

plt.figure(figsize=(10,5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("AAPL Stock Price Analysis")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()