# -*- coding: utf-8 -*-
"""test 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiA9FcMhuLQCyx6s2oYG9ICPKIsUDRaQ
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("task 1.xlsx")

df.head()

print(df.tail())

print(df.info())

print(df.isnull().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

print(df.head(10))

print("Highest Price:", df["High"].max())
print("Lowest Price:", df["Low"].min())
print("Average Closing Price:", df["Close"].mean())

df["Daily Price Change"] = df["Close"].diff()

print(df[["Date", "Close", "Daily Price Change"]])

plt.figure(figsize=(10,5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("AAPL Stock Price Analysis")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df["Daily Price Change"]=df["Close"].diff()
print("\nDaily Price Change:")
print(df[["Date"]].head(10))

print(df[["Date", "Close", "Daily Price Change"]].head(10))

# Calculate 'Loss' based on 'Daily Price Change'
# If the daily price change is negative (a loss), take its absolute value; otherwise, it's 0.
df["Loss"] = df["Daily Price Change"].apply(lambda x: abs(x) if x < 0 else 0)

print("\nLoss:")
print(df[["Date", "Close", "Loss"]])

total_loss = df["Loss"].sum()

print("\nTotal Loss:", total_loss)